### ISSUE TITLE
Push to f-droid

### ISSUE THREAD

**Issue by ways** [cozy-labs/cozy-mobile#22]
Please make the app available in f-droid, for those without Google Play.

**Comment by dkm** [comment]
+1 or at least provide an apk

**Comment by aenario** [comment]
To be published to F-Droid, we need to make a fully reproducible build from this repository sources. However, we use cordova, so the build do involve node, npm, cordova, the android sdk. Which (if we follow the rules of fdroid strictly) we will also need to build from source.
I am not saying it is impossible, but we dont have he time to do it these days. (PR Welcome)



We provide the APK and its hash in the cozy.io doc : http://cozy.io/mobile/files.html#related-resources
I agree it might not be the easiest place to find (just had trouble myself). Where do you think will be the best place to display it ?

**Comment by dkm** [comment]
What about a download on GH directly ? k-9 uses that and it works great (at least from a user pov)! See : https://github.com/k9mail/k-9/releases

**Comment by dkm** [comment]
Or even in the README.md displayed on the GH page (that's where I looked for it)

**Comment by aenario** [comment]
Just done both.

Thanks @dkm for your feedback.

@ways , does the current status (files hosted on github and on cozy.io) cover your needs ? Or should i keep the issue open for someone (maybe us in a few months) to work on the Fdroid build script ?

**Comment by dkm** [comment]
Thanks !!

**Comment by ways** [comment]
@aenario This covers it just fine, thank you. Thanks for response!
